### ISSUE TITLE
other data

### ISSUE THREAD

**Issue by dedioweb** [mediafigaro/google-analytics-api-symfony#11]
The bundle is perfect, it works well.
I wish I could display other data than the default data present in the controller / Services.
Example, display the list of countries, display the map ... but I do not see how to proceed.
Can you explain it to us?
Thank you

**Comment by mediafigaro** [comment]
Hello, thanks I kept it simple and straight to the point. Though, it should be improved with more methods. You can have a look at this fork : https://github.com/lhadjadj/google-analytics-api-symfony @lhadjadj you may find what you're looking for.

**Comment by mediafigaro** [comment]
I've introduced a new public method to handle metrics + dimensions (& sorting) https://github.com/mediafigaro/google-analytics-api-symfony#11
