### ISSUE TITLE
How to fetch data for a specific url ?

### ISSUE THREAD

**Issue by janjango** [mediafigaro/google-analytics-api-symfony#13]
Could you show me please the way to fetch data for a specific url ?
For example `/example-page`
Thanks.

**Comment by mediafigaro** [comment]
Hello ! Sorry for the delay, here is the structure with $pagePath used in the filter dimension : 

            $analyticsService = $this->get('google_analytics_api.api');

            $filterDimension = [   // dimension
                'dimension_name'    =>  'pagePath',
                'operator'          =>  'EXACT',
                'expressions'       =>  [
                    $pagePath
                ]
            ];

            $data = $analyticsService->getDataDateRangeMetricsDimensions(
                $view_id,
                $date_start,//'2018-01-01',   // date start
                $date_end, //'today',        // date end
                $metrics, //['sessions','users','percentNewSessions','bounceRate'],             
                $dimensions, //['source','campaign','pagePath','fullReferrer','sourceMedium'],
                [   // order metric and/or dimension
                    'fields'    =>  ['sessions'],
                    'order'     =>  'descending'
                ],
                null,
                $filterDimension
            );
