### ISSUE TITLE
Pull more than 1000 results

### ISSUE THREAD

**Issue by emirii** [mediafigaro/google-analytics-api-symfony#14]
Hello, sorry if this is obvious, but I looked and couldn't find it. I need to pull more than 1000 results, which is all this function is giving me. Is there a function for paginating past 1000? Or is this a hard limit at this time? My code is pretty straight forward taken from the code samples.

```
        $data = $analyticsService->getDataDateRangeMetricsDimensions(
            '175227836',       // viewid
            $lastMonthStart,   // date start
            $lastMonthEnd,     // date end
            ['pageviews'],     // metric
            ['pagePath']       // dimension
            //[],              // sorting
            //[],              // filter metric
            //[]               // filter demension
        );
```

Thank you!

**Comment by mediafigaro** [comment]
hello, did you see the doc : https://developers.google.com/analytics/devguides/reporting/core/v3/reference
this should be added : 

max-results

Optional.
Maximum number of rows to include in this response. You can use this in combination with start-index to retrieve a subset of elements, or use it alone to restrict the number of returned elements, starting with the first. If max-results is not supplied, the query returns the default maximum of 1000 rows.
The Analytics Core Reporting API returns a maximum of 10,000 rows per request, no matter how many you ask for. It can also return fewer rows than requested, if there aren't as many dimension segments as you expect. For instance, there are fewer than 300 possible values for ga:country, so when segmenting only by country, you can't get more than 300 rows, even if you set max-results to a higher value.

**Comment by hoannv** [comment]
@mediafigaro Can you add new parameters (MaxResults and StartIndex) to getDataDateRangeMetricsDimensions? So we can get more than 1000 rows.

**Comment by emirii** [comment]
Hi from what I learned is 1,000 the max. You have to pay google a ton of money to get more than 1,000 rows from analytics... Thank you mediafigaro.
