### ISSUE TITLE
Can't load bundle from AppKernel

### ISSUE THREAD

**Issue by PokeRstarrr** [mediafigaro/google-analytics-api-symfony#5]
I have an issue with your bundle, It's impossible for me to load the bundle from AppKernel.

If I use the statement statued in the doc, `new MediaFigaro\GoogleAnalyticsApi\GoogleAnalyticsApi(),`
Firstly my IDE don't recognize the path and secondly Symfony returning this error :

> The autoloader expected class "MediaFigaro\GoogleAnalyticsApi\GoogleAnalyticsApi" to be defined in file "C:\wamp64\www\leadingame\vendor\composer/../mediafigaro/google-analytics-api-symfony\GoogleAnalyticsApi.php". The file was found but the class was not in it, the class name or namespace probably has a typo.

And if I use the following statement, `new MediaFigaro\Analytics\GoogleAnalyticsApi(),`
My IDE recognize the path but Symfony returning an error too :

> Attempted to load class "GoogleAnalyticsApi" from namespace "MediaFigaro\Analytics".
> Did you forget a "use" statement for another namespace?

The problem seem to be really specific to this bundle, no problem with the others, so if anyone have a answer to this issue i'm taking it :)

Thanks per advance!
PokeRstarrr

**Comment by kendrick-k** [comment]
Hello yes sorry the latest code got messy because of a naming changes, now it's fixed (1.0) and tested. For which project would you use this bundle ? Best

**Comment by mediafigaro** [comment]
it's ok for you ?
