### ISSUE TITLE
Invalid JWT: Token must be a short-lived token and in a reasonable timeframe

### ISSUE THREAD

**Issue by osmanyz** [mediafigaro/google-analytics-api-symfony#7]
it's a connection problem?

Invalid JWT: Token must be a short-lived token and in a reasonable timeframe

```
{
"error": "invalid_grant",
"error_description": "Invalid JWT: Token must be a short-lived token and in a reasonable timeframe"
}

```
can you help me?

Thanks.

**Comment by mediafigaro** [comment]
Hello, isn't it a clock problem, did you googled it eg : http://stackoverflow.com/questions/36189612/token-must-be-a-short-lived-token-and-in-a-reasonable-timeframe ? Best

**Comment by DonOndeje** [comment]
Hello, this is a system clock problem...on windows 10, change let the system set the time automatically

**Comment by rukshar69** [comment]
I had the same problem when using Google Firebase with Spring boot. I am using Windows 10. I just had to go to time settings and change everything to automatic.
