### ISSUE TITLE
Get detailed data day per day

### ISSUE THREAD

**Issue by drazik** [mediafigaro/google-analytics-api-symfony#8]
Hello,

I am trying to build a dashboard that display some graphs like these ones : 

![analytics](https://cloud.githubusercontent.com/assets/1606068/22503448/165b7fda-e872-11e6-887a-1b46ea5a4d56.png)

I looked at your DebugController to see how to use the bundle and I successfuly retrieved data between 2 dates. But I get the total, not the detailed data day per day that I can use to render my graphs. That's why I was wondering if there is a way to get the detailed data.

Thank you !

**Comment by mediafigaro** [comment]
Hello ! Have a look at the doc : https://developers.google.com/analytics/devguides/reporting/core/v4/basics there is at least multiple date ranges & more to search - I'm not aware of a day per day API result. It's an Google Analytics API topic, hope you can find something & the API offers it..

**Comment by mediafigaro** [comment]
See you place Sainte-Marthe !

**Comment by drazik** [comment]
I just needed to use the ga:date dimension. I'm closing the issue since it is absolutely not related to this bundle, sorry ;)

**Comment by mediafigaro** [comment]
No worries, if you have some ideas to extend this bundle, regarding your needs don't hesitate.
