### ISSUE TITLE
Implement Dimension

### ISSUE THREAD

**Issue by lhadjadj** [mediafigaro/google-analytics-api-symfony#9]
Hi all,
It will fine to get dimension service like metric. 
I am just make a fork and i am introduce a new service to get dimensions like ga:browser / ga:user.
Would you like my codes ?
Bye

**Comment by mediafigaro** [comment]
Hello yes sure, it looks very interesting !

**Comment by mediafigaro** [comment]
pull request ?

**Comment by mediafigaro** [comment]
I've introduced a new public method to handle metrics + dimensions (& sorting) https://github.com/mediafigaro/google-analytics-api-symfony#11
